version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/frontend:rw
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3010
      - IP=192.168.0.33
      - PORT=3001
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3010"
    volumes:
      - ./backend/src:/backend/src:rw
      - ./backend/data:/backend/data:rw
    environment:
      - NODE_ENV=production
      - JWT_SECRET=d64a03684f62aa62a166c3c736cf8ee34176106e009d2a41167787b27eizhhfbihzebcibricyzgiebzihvbirbzvirbvoeurnviebvibv
      - PORT=3010
    networks:
      - app-network

networks:
  app-network:
    driver: bridge